name: Build and Push to ECR

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'deploy/**'
      - 'README.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'deploy/**'
      - 'README.md'


jobs:
  docker:
    name: Build and Push Docker Image to ECR
    runs-on: ubuntu-22.04-arm
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed for git describe

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Generate Image Tag
        id: generate_tag
        run: |
          # Use git describe if tag available, otherwise use date-based dev tag
          IMAGE_TAG=$(git describe --tags --always --dirty 2>/dev/null || echo "dev-$(date +%Y%m%d-%H%M%S)")
          echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_ENV
          echo "Image tag: ${IMAGE_TAG}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::021891583673:role/github-actions"
          aws-region: us-east-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push to ECR
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/arm64
          push: true
          tags: |
            021891583673.dkr.ecr.us-east-2.amazonaws.com/openflagr:latest
            021891583673.dkr.ecr.us-east-2.amazonaws.com/openflagr:${{ env.IMAGE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            VERSION=${{ env.IMAGE_TAG }}
